###################################################################

# Created by write_sdc on Sun Feb  6 14:50:52 2022

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {PC[31]}]
set_load -pin_load 3.40189 [get_ports {PC[30]}]
set_load -pin_load 3.40189 [get_ports {PC[29]}]
set_load -pin_load 3.40189 [get_ports {PC[28]}]
set_load -pin_load 3.40189 [get_ports {PC[27]}]
set_load -pin_load 3.40189 [get_ports {PC[26]}]
set_load -pin_load 3.40189 [get_ports {PC[25]}]
set_load -pin_load 3.40189 [get_ports {PC[24]}]
set_load -pin_load 3.40189 [get_ports {PC[23]}]
set_load -pin_load 3.40189 [get_ports {PC[22]}]
set_load -pin_load 3.40189 [get_ports {PC[21]}]
set_load -pin_load 3.40189 [get_ports {PC[20]}]
set_load -pin_load 3.40189 [get_ports {PC[19]}]
set_load -pin_load 3.40189 [get_ports {PC[18]}]
set_load -pin_load 3.40189 [get_ports {PC[17]}]
set_load -pin_load 3.40189 [get_ports {PC[16]}]
set_load -pin_load 3.40189 [get_ports {PC[15]}]
set_load -pin_load 3.40189 [get_ports {PC[14]}]
set_load -pin_load 3.40189 [get_ports {PC[13]}]
set_load -pin_load 3.40189 [get_ports {PC[12]}]
set_load -pin_load 3.40189 [get_ports {PC[11]}]
set_load -pin_load 3.40189 [get_ports {PC[10]}]
set_load -pin_load 3.40189 [get_ports {PC[9]}]
set_load -pin_load 3.40189 [get_ports {PC[8]}]
set_load -pin_load 3.40189 [get_ports {PC[7]}]
set_load -pin_load 3.40189 [get_ports {PC[6]}]
set_load -pin_load 3.40189 [get_ports {PC[5]}]
set_load -pin_load 3.40189 [get_ports {PC[4]}]
set_load -pin_load 3.40189 [get_ports {PC[3]}]
set_load -pin_load 3.40189 [get_ports {PC[2]}]
set_load -pin_load 3.40189 [get_ports {PC[1]}]
set_load -pin_load 3.40189 [get_ports {PC[0]}]
set_load -pin_load 3.40189 [get_ports {MAR[31]}]
set_load -pin_load 3.40189 [get_ports {MAR[30]}]
set_load -pin_load 3.40189 [get_ports {MAR[29]}]
set_load -pin_load 3.40189 [get_ports {MAR[28]}]
set_load -pin_load 3.40189 [get_ports {MAR[27]}]
set_load -pin_load 3.40189 [get_ports {MAR[26]}]
set_load -pin_load 3.40189 [get_ports {MAR[25]}]
set_load -pin_load 3.40189 [get_ports {MAR[24]}]
set_load -pin_load 3.40189 [get_ports {MAR[23]}]
set_load -pin_load 3.40189 [get_ports {MAR[22]}]
set_load -pin_load 3.40189 [get_ports {MAR[21]}]
set_load -pin_load 3.40189 [get_ports {MAR[20]}]
set_load -pin_load 3.40189 [get_ports {MAR[19]}]
set_load -pin_load 3.40189 [get_ports {MAR[18]}]
set_load -pin_load 3.40189 [get_ports {MAR[17]}]
set_load -pin_load 3.40189 [get_ports {MAR[16]}]
set_load -pin_load 3.40189 [get_ports {MAR[15]}]
set_load -pin_load 3.40189 [get_ports {MAR[14]}]
set_load -pin_load 3.40189 [get_ports {MAR[13]}]
set_load -pin_load 3.40189 [get_ports {MAR[12]}]
set_load -pin_load 3.40189 [get_ports {MAR[11]}]
set_load -pin_load 3.40189 [get_ports {MAR[10]}]
set_load -pin_load 3.40189 [get_ports {MAR[9]}]
set_load -pin_load 3.40189 [get_ports {MAR[8]}]
set_load -pin_load 3.40189 [get_ports {MAR[7]}]
set_load -pin_load 3.40189 [get_ports {MAR[6]}]
set_load -pin_load 3.40189 [get_ports {MAR[5]}]
set_load -pin_load 3.40189 [get_ports {MAR[4]}]
set_load -pin_load 3.40189 [get_ports {MAR[3]}]
set_load -pin_load 3.40189 [get_ports {MAR[2]}]
set_load -pin_load 3.40189 [get_ports {MAR[1]}]
set_load -pin_load 3.40189 [get_ports {MAR[0]}]
set_load -pin_load 3.40189 [get_ports {MDRW[31]}]
set_load -pin_load 3.40189 [get_ports {MDRW[30]}]
set_load -pin_load 3.40189 [get_ports {MDRW[29]}]
set_load -pin_load 3.40189 [get_ports {MDRW[28]}]
set_load -pin_load 3.40189 [get_ports {MDRW[27]}]
set_load -pin_load 3.40189 [get_ports {MDRW[26]}]
set_load -pin_load 3.40189 [get_ports {MDRW[25]}]
set_load -pin_load 3.40189 [get_ports {MDRW[24]}]
set_load -pin_load 3.40189 [get_ports {MDRW[23]}]
set_load -pin_load 3.40189 [get_ports {MDRW[22]}]
set_load -pin_load 3.40189 [get_ports {MDRW[21]}]
set_load -pin_load 3.40189 [get_ports {MDRW[20]}]
set_load -pin_load 3.40189 [get_ports {MDRW[19]}]
set_load -pin_load 3.40189 [get_ports {MDRW[18]}]
set_load -pin_load 3.40189 [get_ports {MDRW[17]}]
set_load -pin_load 3.40189 [get_ports {MDRW[16]}]
set_load -pin_load 3.40189 [get_ports {MDRW[15]}]
set_load -pin_load 3.40189 [get_ports {MDRW[14]}]
set_load -pin_load 3.40189 [get_ports {MDRW[13]}]
set_load -pin_load 3.40189 [get_ports {MDRW[12]}]
set_load -pin_load 3.40189 [get_ports {MDRW[11]}]
set_load -pin_load 3.40189 [get_ports {MDRW[10]}]
set_load -pin_load 3.40189 [get_ports {MDRW[9]}]
set_load -pin_load 3.40189 [get_ports {MDRW[8]}]
set_load -pin_load 3.40189 [get_ports {MDRW[7]}]
set_load -pin_load 3.40189 [get_ports {MDRW[6]}]
set_load -pin_load 3.40189 [get_ports {MDRW[5]}]
set_load -pin_load 3.40189 [get_ports {MDRW[4]}]
set_load -pin_load 3.40189 [get_ports {MDRW[3]}]
set_load -pin_load 3.40189 [get_ports {MDRW[2]}]
set_load -pin_load 3.40189 [get_ports {MDRW[1]}]
set_load -pin_load 3.40189 [get_ports {MDRW[0]}]
set_load -pin_load 3.40189 [get_ports cs_MDRW]
set_load -pin_load 3.40189 [get_ports rd_wr_n_MDRW]
create_clock [get_ports clk]  -name MY_CLK  -period 3.56  -waveform {0 1.78}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports rst_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {IR[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {MDRR[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MAR[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {MDRW[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports cs_MDRW]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports rd_wr_n_MDRW]
